version = 1

# Tool-generated or configuration files.
[[annotations]]
path = [
  ".dockerignore",
  ".editorconfig",
  ".golangci.yml",
  ".gitignore",
  ".licensed.yml",
  ".licenses/**",
  "dprint.json",
  "go.mod",
  "go.sum",
  ".codespellrc",
  ".editorconfig-checker.json",
  ".npmrc",
  "Taskfile.yml",
  "package-lock.json",
  "package.json",
  "poetry.lock",
  "pyproject.toml",
  ".markdown-link-check.json",
  ".markdownlint.yml",
  ".markdownlintignore",
  "zsyscall_windows.go",
]
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "BSD-3-Clause"
